version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    groups:
      all-version-updates:
        applies-to: version-updates
        #patterns:
        #  - "*"
      security-by-dep:
        applies-to: security-updates
        group-by: dependency-name
